language: go

install:
    - go get github.com/alexflint/go-arg
    - go get github.com/hpcloud/tail
    - go get github.com/paulbellamy/ratecounter
    - go get github.com/sirupsen/logrus
    - go get github.com/tidwall/gjson

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
