language: go

install:
    - go get -v -t -d ./...

go:
  - 1.8
  - 1.9
  # - 1.11 // go-arg has issues, should get rid of it. 
  - 1.11
  - tip

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
