language: go

install:
    - go get github.com/alexflint/go-arg
    - go get github.com/hpcloud/tail
    - go get github.com/paulbellamy/ratecounter
    - go get github.com/sirupsen/logrus
    - go get github.com/tidwall/gjson
    - go get github.com/alecthomas/participle

go:
  - 1.7
  - 1.8
  - tip

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
