# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
      - image: circleci/golang:1.9
      - image: circleci/golang:1.11
      - image: circleci/golang:latest

    working_directory: /go/src/github.com/shadyabhi/jqtop
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go -race test -v ./...
